insert into "стая" values (default, 'стая 1');
insert into "стая" values (default, 'смотрящего на луну');

insert into "питекантроп" values (default, 'смотрящий', 'мужской', 2);
insert into "питекантроп" values (default, 'ден', 'мужской', 2);
insert into "питекантроп" values (default, 'кларк', 'мужской', 2);
insert into "питекантроп" values (default, 'джон', 'мужской', 2);
insert into "питекантроп" values (default, 'мик', 'мужской', 1);
insert into "питекантроп" values (default, 'гларк', 'мужской', 1);
insert into "питекантроп" values (default, 'стафим', 'мужской', 1);
insert into "питекантроп" values (default, 'аля', 'женский', 1);
insert into "питекантроп" values (default, 'толян', 'мужской', 1);
insert into "питекантроп" values (default, 'никитос', 'мужской', 1);
insert into "питекантроп" values (default, 'правая рука', 'мужской', 1);
insert into "питекантроп" values (default, 'левая рука', 'мужской', 1);
insert into "питекантроп" values (default, 'тор', 'мужской', 1);
insert into "питекантроп" values (default, 'аленка', 'женский', 1);
insert into "питекантроп" values (default, 'настя', 'женский', 1);
insert into "питекантроп" values (default, 'валера', 'мужской', 1);
insert into "питекантроп" values (default, 'женя', 'женский', 1);
insert into "питекантроп" values (default, 'влад', 'мужской', 1);
insert into "питекантроп" values (default, 'марина', 'женский', 1);
insert into "питекантроп" values (default, 'халк', 'мужской', 1);
insert into "питекантроп" values (default, 'джек', 'мужской', 1);
insert into "питекантроп" values (default, 'карлос', 'женский', 1);
insert into "питекантроп" values (default, 'джейм', 'мужской', 1);
insert into "питекантроп" values (default, 'таня', 'женский', 1);
insert into "питекантроп" values (default, 'зоя', 'женский', 1);
insert into "питекантроп" values (default, 'тростия', 'женский', 1);
insert into "питекантроп" values (default, 'ждун', 'мужской', 1);
insert into "питекантроп" values (default, 'кувалда', 'женский', 1);
insert into "питекантроп" values (default, 'просто', 'мужской', 1);
insert into "питекантроп" values (default, 'жома', 'мужской', 1);
insert into "питекантроп" values (default, 'зюзя', 'женский', 1);
insert into "питекантроп" values (default, 'фара', 'мужской', 1);
insert into "питекантроп" values (default, 'гром', 'мужской', 1);
insert into "питекантроп" values (default, 'вики', 'женский', 1);

insert into "локация" values (default, 'левый берег');
insert into "локация" values (default, 'правый берег');

insert into "расположение_питекантропа" values (1, 2);
insert into "расположение_питекантропа" values (2, 2);
insert into "расположение_питекантропа" values (3, 2);
insert into "расположение_питекантропа" values (4, 2);
insert into "расположение_питекантропа" values (5, 1);
insert into "расположение_питекантропа" values (6, 1);
insert into "расположение_питекантропа" values (7, 1);
insert into "расположение_питекантропа" values (8, 1);
insert into "расположение_питекантропа" values (9, 1);
insert into "расположение_питекантропа" values (10, 1);
insert into "расположение_питекантропа" values (11, 1);
insert into "расположение_питекантропа" values (12, 1);
insert into "расположение_питекантропа" values (13, 1);
insert into "расположение_питекантропа" values (14, 1);
insert into "расположение_питекантропа" values (15, 1);
insert into "расположение_питекантропа" values (16, 1);
insert into "расположение_питекантропа" values (17, 1);
insert into "расположение_питекантропа" values (18, 1);
insert into "расположение_питекантропа" values (19, 1);
insert into "расположение_питекантропа" values (20, 1);
insert into "расположение_питекантропа" values (21, 1);
insert into "расположение_питекантропа" values (22, 1);
insert into "расположение_питекантропа" values (23, 1);
insert into "расположение_питекантропа" values (24, 1);
insert into "расположение_питекантропа" values (25, 1);
insert into "расположение_питекантропа" values (26, 1);
insert into "расположение_питекантропа" values (27, 1);
insert into "расположение_питекантропа" values (28, 1);
insert into "расположение_питекантропа" values (29, 1);
insert into "расположение_питекантропа" values (30, 1);
insert into "расположение_питекантропа" values (31, 1);
insert into "расположение_питекантропа" values (32, 1);
insert into "расположение_питекантропа" values (33, 1);
insert into "расположение_питекантропа" values (34, 1);

insert into "действие" values (default, 'завидеть', 1, 'now', NULL);
insert into "действие" values (default, 'подпрыгивать', 1, 'now', 'now');
insert into "действие" values (default, 'махать руками', 1, 'now', 'now');
insert into "действие" values (default, 'кричать', 1, 'now', 'now');
insert into "действие" values (default, 'подпрыгивать', 2, 'now', 'now');
insert into "действие" values (default, 'махать руками', 2, 'now', 'now');
insert into "действие" values (default, 'кричать', 2, 'now', 'now');
insert into "действие" values (default, 'завидеть', 2, 'now', NULL);

insert into "действие_type" values (default, 'комуникация с питекантропом', 1, NULL, 1);
insert into "действие_type" values (default, 'комуникация со стаей и питекантропом', 2, 2, 1);
insert into "действие_type" values (default, 'комуникация со стаей и питекантропом', 3, 2, 1);
insert into "действие_type" values (default, 'комуникация со стаей и питекантропом', 4, 2, 1);
insert into "действие_type" values (default, 'комуникация со стаей', 5, 1, NULL);
insert into "действие_type" values (default, 'комуникация со стаей', 6, 1, NULL);
insert into "действие_type" values (default, 'комуникация со стаей', 7, 1, NULL);
insert into "действие_type" values (default, 'комуникация со стаей', 8, 1, NULL);

insert into "коммуникация_стаи" values (1, 1);
insert into "коммуникация_стаи" values (2, 1);
insert into "коммуникация_стаи" values (3, 1);
insert into "коммуникация_стаи" values (4, 1);
insert into "коммуникация_стаи" values (5, 2);
insert into "коммуникация_стаи" values (6, 2);
insert into "коммуникация_стаи" values (7, 2);

insert into "коммуникация_питекантропа" values (8, 1);